version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  database:
    build:
      context: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"

  mobile:
    build:
      context: ./mobile
    ports:
      - "${MOBILE_PORT}:8081"
    environment:
      BACKEND_URL: "http://api.nutriapp.localhost"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - mobile

volumes:
  db_data:
