services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: ["sh", "-c", "dotnet ef database update && dotnet NutriApp.dll"]

  database:
    build:
      context: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nutrikid.io
      PGADMIN_DEFAULT_PASSWORD: NutriApp1@
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: ["npm", "run", "dev"]

  mobile:
    build:
      context: ./mobile
    ports:
      - "${MOBILE_PORT}:8081"
    environment:
      BACKEND_URL: "http://api.nutriapp.localhost"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - mobile

volumes:
  db_data:
  pgadmin_data: